### ISSUE TITLE
Chat Box Layout Issue - on bigger screens 6 inch - pixel 3a xl 

### ISSUE THREAD

**Issue by surapuramakhil** [Jamalianpour/Simple-chat-with-flutter#1]
Layouts are not auto extending according to screen sizes. 6 inch

![Screenshot from 2020-04-26 22-41-56](https://user-images.githubusercontent.com/9161543/80314509-7e1df180-880f-11ea-8eac-0c8bbe1587d1.png)

**Comment by surapuramakhil** [comment]
received messages are not intended

**Comment by Jamalianpour** [comment]
I fixed it
